export const youtubeSearchQueries = [
  "funny cat videos",
  "best coding tutorials 2024",
  "relaxing piano music 1 hour",
  "how to bake a cake step by step",
  "latest tech news",
  "top 10 Marvel movies ranked",
  "home workout for beginners",
  "travel vlogs in Europe",
  "DIY home decor ideas",
  "gameplay walkthrough Elden Ring",
  "learn Python programming",
  "morning yoga routine",
  "top 10 anime to watch",
  "best movies of 2024",
  "quick and easy recipes",
  "science documentaries",
  "history of space exploration",
  "live music concerts",
  "best gaming laptops 2024",
  "drawing tutorials for beginners",
  "amazing nature videos",
  "comedy skits compilation",
  "motivational speeches",
  "TED talks worth watching",
  "fitness transformation journeys",
  "virtual reality experiences",
  "coding challenges for beginners",
  "latest smartphone reviews",
  "car reviews and test drives",
  "stand-up comedy specials",
  "magic tricks revealed",
  "educational videos for kids",
  "how to learn a new language",
  "weight loss tips that work",
  "football match highlights",
  "inspirational quotes",
  "street food tours around the world",
  "home cleaning hacks",
  "personal finance tips",
  "interior design inspiration",
  "vintage fashion trends",
  "anime opening songs",
  "celebrity interviews",
  "how to play guitar",
  "popular video game trailers",
  "camping gear reviews",
  "robotics tutorials",
  "DIY science experiments",
  "top travel destinations",
  "live weather updates",
  "best podcasts to listen to",
  "mystery documentaries",
  "pet training tips",
  "gardening for beginners",
  "how to meditate effectively",
  "best luxury watches",
  "street art and graffiti",
  "best wine brands",
  "virtual museum tours",
  "coding for kids",
  "classic rock playlists",
  "top trending TikToks",
  "eco-friendly living tips",
  "hiking adventure blogs",
  "book reviews and recommendations",
  "self-defense techniques",
  "how to draw anime characters",
  "most expensive houses",
  "luxury car collections",
  "video editing tutorials",
  "street photography tips",
  "space exploration news",
  "how to knit a sweater",
  "top stand-up comedians",
  "art tutorials for beginners",
  "crypto trading tips",
  "how to cook vegan meals",
  "wedding planning ideas",
  "amazing science facts",
  "bizarre conspiracy theories",
  "best action movie trailers",
  "life hacks everyone should know",
  "virtual fitness classes",
  "unboxing gadgets 2024",
  "how to write a book",
  "best hiking trails",
  "famous movie scenes explained",
  "music theory lessons",
  "best fantasy novels of all time",
  "budget travel tips",
  "astronomy for beginners",
  "how to grow succulents",
  "top 10 horror games",
  "luxury fashion brands review",
  "how to build a gaming PC",
  "best chess tutorials",
  "relaxing rain sounds",
  "how to make coffee art",
  "best LEGO sets for adults",
  "DIY holiday decorations",
  "puppy training tips",
  "movie theories that make sense",
  "animated shorts to watch",
  "world's largest animals",
  "hidden gems on Netflix",
  "how to make candles",
  "fun facts about space",
  "best desserts in the world",
  "origami tutorials for kids",
  "classic movie recommendations",
  "fitness challenges for beginners",
  "how to start a podcast",
  "best electric cars 2024",
  "how to draw realistic eyes",
  "top 10 soccer players",
  "urban exploration videos",
  "best makeup tutorials",
  "underwater photography tips",
  "how to master public speaking",
  "celebrity fashion fails",
  "DIY woodworking projects",
  "wildlife documentaries",
  "street magic tricks",
  "how to make slime",
  "best historical movies",
  "luxury yacht tours",
  "scariest ghost stories",
  "how to start a business",
  "karaoke songs for beginners",
  "best meditation apps",
  "camping tips for beginners",
  "top 10 arcade games",
  "world's tallest buildings",
  "how to make money online",
  "weirdest world records",
  "best desserts to try",
  "virtual reality horror games",
  "anime reviews and recommendations",
  "fun outdoor games for kids",
  "top 10 productivity apps",
  "how to play chess for beginners",
  "best romantic comedies",
  "crazy science experiments",
];
